version: '2'
services:
  api:
    expose:
      - '3000'
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules/
    command: bash start.debug.sh
    depends_on:
      - message-queue
    environment:
      - NODE_ENV=production
      - AMPQ_ADDRESS=amqp://message-queue:5672
    links:
      - message-queue
  # cron:
  #   image: pushkin/cron:latest
  #   build:
  #     context: ./cron
  #     dockerfile: Dockerfile
  #   environment:
  #     - AMPQ_ADDRESS=amqp://message-queue:5672
  #     - API_ADDRESS=http://api:3000/api
  #     - DATABASE_URL=postgres://postgres@db:5432/dev
  #     - TRANSACTION_DATABASE_URL=postgres://postgres@transactiondb:5432/transactions-dev
  #   links:
  #     - message-queue
  #     - db
  #     - transactiondb
  #     - api
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=postgres
    expose:
      - '5432'
    ports:
      - '5432:5432'
  db-worker:
    build:
      context: ./db-worker
      dockerfile: Dockerfile
    volumes:
      - ./db-worker:/usr/src/app
      - /usr/src/app/node_modules/
    command: bash start.debug.sh
    depends_on:
      - message-queue
    environment:
      - AMPQ_ADDRESS=amqp://message-queue:5672
      - DATABASE_URL=postgres://postgres@db:5432/dev
      - TRANSACTION_DATABASE_URL=postgres://postgres@transactiondb:5432/transactions-dev
    links:
      - message-queue
      - db
      - transactiondb
  message-queue:
    image: rabbitmq:management
    expose:
      - '5672'
    ports:
      - '8080:15672'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '80:80'
    links:
      - api
    volumes:
      - ./front-end/public:/var/www/html
  transactiondb:
    image: pushkin/transactiondb:latest
    build:
      context: ./
      dockerfile: Dockerfile.transactiondb
    environment:
      - POSTGRES_DB=transactions-dev
      - POSTGRES_USER=postgres
    expose:
      - '5432'
    ports:
      - '5433:5432'
  listener-quiz:
    build:
      context: ./workers/listener-quiz
      dockerfile: Dockerfile
    volumes:
      - ./workers/listener-quiz:/usr/src/app
    command: bash start.debug.sh
    depends_on:
      - message-queue
    environment:
      - AMPQ_ADDRESS=amqp://message-queue:5672
      - QUEUE=listener-quiz
    links:
      - message-queue
  front-end:
    build:
      context: ./front-end
    volumes:
      - ./front-end:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - '8000:8000'
  pushkin-mailer:
    build:
      context: ./pushkin-mailer
    volumes:
      - ./pushkin-mailer:/usr/src/app
      - /usr/src/app/node_modules/
    command: bash start.debug.sh
    depends_on:
      - message-queue
    environment:
      - SENDGRID_API_KEY=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
      - AMPQ_ADDRESS=amqp://message-queue:5672
    links:
      - message-queue