site_name: Pushkin
theme:
  name: material
  favicon: 'assets/pushkin_bw_no_text.png'
  logo: 'assets/pushkin_bw_no_text.png'
  features:
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: pink
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: pink
copyright: 'Copyright &copy; 2015-2024 Joshua Hartshorne'
site_description: 'Pushkin provides a customizable, scalable ecosystem for massive online psychological experiments.'
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
extra:
  version:
    provider: mike
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
plugins:
  - search
  - mike:
      # Set to true for subsequent releases
      version_selector: false
  - open-in-new-tab
  - table-reader
repo_url: https://github.com/pushkin-consortium/pushkin
repo_name: pushkin-consortium/pushkin
nav:
- Home: 'index.md'
- Getting Started:
  - Installation: 'getting-started/installation.md'
  - Quickstart tutorial: 'getting-started/quickstart.md'
  - Deploying to AWS: 'getting-started/deploying-to-aws.md'
  - Simple Experiment Tutorial: 'getting-started/simple-experiment-tutorial.md'
- Site templates:
  - Overview of site templates: 'site-templates/site-templates-overview.md'
  - site-basic: 'site-templates/site-basic.md'
- Experiment templates:
  - Overview of experiment templates: 'exp-templates/exp-templates-overview.md'
  - exp-basic: 'exp-templates/exp-basic.md'
  - exp-lexical-decision: 'exp-templates/exp-lexical-decision.md'
  - exp-grammaticality-judgment: 'exp-templates/exp-grammaticality-judgment.md'
  - exp-self-paced-reading: 'exp-templates/exp-self-paced-reading.md'
- Packages:
  - Overview of packages: 'packages/packages-overview.md'
  - pushkin-cli: 'packages/pushkin-cli.md'
  - pushkin-api: 'packages/pushkin-api.md'
  - pushkin-client: 'packages/pushkin-client.md'
  - pushkin-worker: 'packages/pushkin-worker.md'
- Developers: 
  - Contributions: 'developers/contributions.md'
  - Documentation: 'developers/documentation.md'
  - Developing with Pushkin: 'developers/developing-with-pushkin.md'
  - Getting Started on Development: 'developers/getting-started-on-development.md'
  - Overview of Technologies: 'developers/overview-of-tech.md'
  - Working with Templates: 'developers/working-with-templates.md'
- Support:
  - FAQs: 'support/faqs.md'
  - Troubleshooting: 'support/troubleshooting.md'
  - GitHub Discussions: 'support/github-discussions.md'
  - Learning Resources: 'support/learning-resources.md'
  - Security: 'support/security.md'
- About:
  - About Pushkin: 'about/about-pushkin.md'
  - License: 'about/pushkin-license.md'