site_name: Pushkin
theme:
  name: material
  favicon: 'img/pushkin_bw_w_text.png'
  logo: 'img/pushkin_bw_w_text.png'
  features:
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.path
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep orange
      accent: deep purple
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep orange
      accent: deep purple
extra:
  version:
    provider: mike
repo_url: https://github.com/pushkin-consortium/pushkin
repo_name: pushkin-constortium/pushkin
nav:
- Introduction: 'README.md'
- Getting Started:
  - Installing Pushkin and Dependencies: 
    - Choose Your OS: 'getting-started/installing-pushkin-and-dependencies/README.md'
    - macOS: 'getting-started/installing-pushkin-and-dependencies/macos-install.md'
    - Windows 10:
      - Windows Subsystem for Linux: 'getting-started/installing-pushkin-and-dependencies/windows-install.md'
      - AWS EC2 Instance: 'getting-started/installing-pushkin-and-dependencies/ec2-install.md'
    - Ubuntu Linux: 'getting-started/installing-pushkin-and-dependencies/ubuntu-install.md'
  - Quickstart: 
    - Introduction: 'getting-started/quickstart/README.md'
    - Quickstart - Example Outputs: 'getting-started/quickstart/sample_output.md'
  - Deploying to AWS: 
    - Introduction: 'getting-started/deploying-to-aws/README.md'
    - Install Required Software: 'getting-started/deploying-to-aws/install-required-software.md'
    - Configure the AWS and ECS CLIs: 'getting-started/deploying-to-aws/configure-aws-and-ecs-clis.md'
    - Register a Domain: 'getting-started/deploying-to-aws/domain-registration.md'
    - Set up Dockerhub: 'getting-started/deploying-to-aws/dockerhub.md'
    - Initialize AWS Deploy: 'getting-started/deploying-to-aws/initializing-aws-deploy.md'
  - Tutorial - Simple Experiment: 
    - Tutorial: 'getting-started/tutorial-simple-experiment.md'
- FAQ: 
  - FAQ: 'faq/FAQ.md'
- Advanced: 
  - Pushkin CLI: 'advanced/pushkin-cli.md'
  - Experiment Templates:
    - Using Experiment Templates: 'advanced/modifying-experiment-templates/README.md'
    - Lexical Decision Template: 'advanced/modifying-experiment-templates/lexical-decision-template.md'
    - Grammaticality Judgement Template: 'advanced/modifying-experiment-templates/grammaticality-judgement-template.md'
    - Self-Paced Reading Template: 'advanced/modifying-experiment-templates/self-paced-reading-template.md'
  - Experiment Component Structure:
    - Structure: 'advanced/experiment-structure/README.md'
    - Experiment Config.yaml Files: 'advanced/experiment-structure/experiment-config-files.md'
    - Experiment Web Page Componenent: 'advanced/experiment-structure/experiment-web-page-component.md'
    - Worker Component, Migration, and Seed: 'advanced/experiment-structure/worker-component-migration-and-seed.md'
  - Modifying a Site: 
    - Details: 'advanced/modifying-site-template/README.md'
    - React Bootstrap: 'advanced/modifying-site-template/react-bootstrap.md'
    - Header & Footer: 'advanced/modifying-site-template/header-and-footer.md'
    - Home Page: 'advanced/modifying-site-template/home-page.md'
    - Findings Page: 'advanced/modifying-site-template/findings-page.md'
    - About Page: 'advanced/modifying-site-template/about-page.md'
    - Feedback Page: 'advanced/modifying-site-template/feedback-page.md'
  - Troubleshooting Pushkin: 'advanced/troubleshooting-pushkin.md'
  - Pushkin Client: 'advanced/pushkin-client.md'
  - Pushkin API:
    - About: 'advanced/pushkin-api/README.md'
    - API-Controller Builder: 'advanced/pushkin-api/api-controller-builder.md'
    - Core API: 'advanced/pushkin-api/core-api.md'
  - Users & Authentication: 'advanced/users-and-authentication.md'
  - Deployment:  
    - Deleting AWS: 'advanced/deploying/awsDeletion.md'
- Developers: 
  - Developing with Pushkin: 'developers/developing-with-pushkin.md'
  - Getting Started on Development: 'developers/getting-started-on-development.md'
  - Overview of Technologies: 'developers/overview-of-tech.md'
  - Working with Templates: 'developers/working-with-templates.md'