#!/bin/bash

# NB: all scripts in /bin expect to be run from pushkin root as the cwd

source '.pushkin/pushkin_config_vars.sh'
source '.pushkin/bin/core.sh'
source "${pushkin_env_file}"

log () { echo "${boldFont}pushkin:${normalFont} ${1}"; }
showUsage () {
        echo "usage: pushkin [make | prep | migrate | seed | build | sync | compile | start | init] [sub-command args]"
}

# route commands
sub_command="${1}"
shift
case "${sub_command}" in
	"make")
		.pushkin/bin/make.sh "$@"
		;;
	"prep")
		.pushkin/bin/prepareFiles.sh "$@"
		;;
	"migrate")
		.pushkin/bin/migrate.sh "$@"
		;;
	"seed")
		.pushkin/bin/seed.sh "$@"
		;;
	"build")
		.pushkin/bin/build.sh "$@"
		;;
	"sync")
		.pushkin/bin/sync.sh "$@"
		;;
	"compile")
		.pushkin/bin/compileFrontEnd.sh "$@"
		;;
	"start")
		docker-compose -f "${pushkin_docker_compose_noDep_file}" up
		;;
	"init")
		.pushkin/bin/init.sh "$@"
		;;
	*)
		showUsage
		die "command ${sub_command} does not exist"
		;;
esac














