# note: if this image name must be changed,
# make sure prepareToDeploy matches up with it in the
# build stage of quiz-specific workers
#
# indentation must match main compose file
#
# image prefix and tag are variables stored in main .env file

  pushkin-testquiz-quiz:
    image: '${image_prefix}/pushkin-testquiz-quiz:${image_tag}'
    command: 'bash start.sh'
    depends_on:
      - "message-queue"
    links:
      - message-queue
    environment:
      - "AMQP_ADDRESS=amqp://message-queue:5672"
      - "DATABASE_URL=postgres://${main_db_user}:${main_db_pass}@${main_db_url}/${main_db_name}"
      - "TRANSACTION_DATABASE_URL=postgres://${transaction_db_user}:${transaction_db_pass}@${transaction_db_url}/${transaction_db_name}"
