#!/bin/bash

# NB: all scripts in /bin expect to be run from pushkin root as the cwd

##############################################
# setup
##############################################

die () { echo "${1}"; exit 1; }
dieCorrupt () { echo "Pushkin project directory is corrupt. Error: ${1}"; exit 2; }
checkPushkinNotCorrupt () {
        # assumes $1 is root path of pushkin
        # and .pushkin/ exists
        root="${1}"

        test_dirs=("${root}/.pushkin/bin")
        for dir in ${test_dirs[@]}; do
                if [ ! -d "${dir}" ]; then
                        dieCorrupt "Missing critical infrastructure directory ${dir}"
                fi
        done

        test_files=("${root}/.pushkin/pushkin_config_vars.sh")
        for file in ${test_files[@]}; do
                if [ ! -f "${file}" ]; then
                        dieCorrupt "Missing critical infrastructure file ${file}"
                fi
        done
}
showUsage () {
        echo "usage: pushkin [make | prep | migrate | seed | build | sync | compile | start | init] [sub-command args]"
}

##############################################
# start
##############################################

# move to root
while [ ! -d "$PWD/.pushkin" ]; do
        if [ $PWD == '/' ]; then
                die "No pushkin project found here or in any above directories"
        fi
        cd ..
done
# will die with error if setup's innapropriate
checkPushkinNotCorrupt $PWD

# setup good enough to function (not an exhaustive check)

$PWD/.tools/pushkin-tools "$@"
