name: Publish documentation

on:
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install poetry using pip
        run: pipx install poetry==1.7.1

      - name: Get current version
        id: version
        run: echo "version=$(node -p "require('./packages/pushkin-cli/package.json').version")" >> "$GITHUB_ENV"

      - name: Remove patch version
        run: echo "version_major_minor=${{ env.version }}" | awk -F. '{print $1"."$2}' >> "$GITHUB_ENV"

      - name: Config git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Deploy docs
        run: |
          yarn docs:deploy ${{ env.version_major_minor }} latest

      - name: Switch to gh-pages branch
        run: git checkout gh-pages

      - name: Push gh-pages branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
