name: E2E tests for basic site template

on:
  workflow_dispatch:
  push:
    branches:
      - actions-testing

jobs:
  site-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build packages
        run: yarn workspaces run build

      - name: Setup a basic Pushkin site
        run: |
          export PATH="$(yarn global bin):$PATH"
          yarn global add yalc
          yarn setup-site basic

      - name: Start the Pushkin site
        run: |
          cd testing
          node ../packages/pushkin-cli/build/index.js start -v
          # Wait up to a minute for the site to start
          for i in {1..12}
          do
            if curl --output /dev/null --silent --head --fail http://localhost:80; then
              break
            fi
            echo 'Waiting for the server to start...'
            sleep 5
          done
      
      - name: Install Playwright browsers
        run: |
          cd testing
          npx playwright install --with-deps
      
      - name: Run end-to-end tests
        run: |
          cd testing
          yarn test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: testing/playwright-report/
          retention-days: 30